version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: olkhovik/foodgram_backend 
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: olkhovik/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: olkhovik/foodgram_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media