# Generated by Django 3.2.3 on 2023-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstuff',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
